general {
    lock_cmd = pidof hyprlock >/dev/null 2>&1 || qs -c caelestia ipc call lock lock
    before_sleep_cmd = qs -c caelestia ipc call lock unlock; loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch dpms on
}
